version: '3'

services:
  backend:
    build: ./backend
    image: backend-image
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    depends_on:
      - mysql-container

  mysql-container:
    build: ./db
    image: mysql-image
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    image: frontend-image
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
