version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    depends_on:
      - mysql-container

  mysql-container:
    build: ./database
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
