name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          npm run test

      - name: Run Application (Optional)
        run: |
          npm start